// Package config loads, validates and persists the Supp configuration file.
package config

import (
	"errors"
	"fmt"
	"net"
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
)

// Config is the root configuration, persisted as /etc/supp/config.toml.
type Config struct {
	Server Server `toml:"server"`
	DNS    DNS    `toml:"dns"`
	Block  Block  `toml:"block"`
	Admin  Admin  `toml:"admin"`
	Log    Log    `toml:"log"`
	WG     WG     `toml:"wg"`
}

// WG holds the WireGuard VPN (phase 2) settings. All-zero values keep the
// module disabled; Enable turns it into the standard defaults.
type WG struct {
	Enabled   bool     `toml:"enabled"`
	Interface string   `toml:"interface"` // kernel link name, e.g. supp0
	Port      int      `toml:"port"`      // UDP listen port
	Subnet    string   `toml:"subnet"`    // tunnel CIDR, server takes .1
	Endpoint  string   `toml:"endpoint"`  // host or host:port peers dial; default server.domain
	// DefaultFullTunnel routes all device traffic through the VPS when true
	// (IP hiding); when false peers default to split-tunnel (DNS + split).
	DefaultFullTunnel bool     `toml:"default_full_tunnel"`
	SplitNetworks     []string `toml:"split_networks"` // CIDRs routed in split mode
}

// Server holds network listener settings.
type Server struct {
	// DataDir stores state: the SQLite database, downloaded lists, ACME certs.
	DataDir string `toml:"data_dir"`
	// Domain is the public DNS name pointing at this VPS (used in per-device
	// DoH URLs and certificate issuance). Empty disables per-device paths.
	Domain string `toml:"domain"`
}

// DNS holds resolver behavior.
type DNS struct {
	Upstreams []Upstream `toml:"upstreams"`
	// Bootstrap are plain-IP DNS servers used only to resolve upstream hostnames.
	Bootstrap []string `toml:"bootstrap"`
	Cache     Cache    `toml:"cache"`
	Listen    Listen   `toml:"listen"`
	Timeout   Duration `toml:"timeout"` // per-upstream query timeout
	EdnsCsr   bool     `toml:"edns_client_subnet"`
}

// Upstream is one DNS upstream. URL uses scheme doh://, dot:// or udp://.
type Upstream struct {
	URL    string `toml:"url"`
	Weight int    `toml:"weight"`
}

// Cache settings.
type Cache struct {
	Size    int      `toml:"size"`     // max entries
	MinTTL  Duration `toml:"min_ttl"`  // clamp cache TTL floor
	MaxTTL  Duration `toml:"max_ttl"`  // clamp cache TTL ceiling
	FailTTL Duration `toml:"fail_ttl"` // negative cache for SERVFAIL
}

// Listen addresses. Empty string disables that listener.
type Listen struct {
	Plain string `toml:"plain"` // udp+tcp :53
	DoT   string `toml:"dot"`   // tls     :853
	DoH   string `toml:"doh"`   // https   :443
}

// Block holds the filtering configuration.
type Block struct {
	Enabled    bool     `toml:"enabled"`
	Lists      []List   `toml:"lists"`
	Allowlist  []string `toml:"allowlist"`
	Denylist   []string `toml:"denylist"`
	Refresh    Duration `toml:"refresh"`
	BlockIPv6  bool     `toml:"block_ipv6"`  // return :: for AAAA of blocked names
	ResponseIP string   `toml:"response_ip"` // custom A response, default 0.0.0.0
}

// List is one remote or local blocklist.
type List struct {
	Name   string `toml:"name"`
	URL    string `toml:"url"`    // file:// paths also accepted
	Format string `toml:"format"` // auto|hosts|domains|adguard
}

// Admin is the local dashboard.
type Admin struct {
	Enabled bool   `toml:"enabled"`
	Listen  string `toml:"listen"`
	Token   string `toml:"token"` // generated by supp init when empty
}

// Log controls request logging. Privacy: off by default.
type Log struct {
	Queries      bool     `toml:"queries"`       // full query log (privacy sensitive)
	Retention    Duration `toml:"retention"`     // how long to keep rows
	CountersOnly bool     `toml:"counters_only"` // keep counts but never domains
}

// Duration wraps time.Duration for TOML string values like "24h".
type Duration time.Duration

// UnmarshalText parses durations via time.ParseDuration.
func (d *Duration) UnmarshalText(b []byte) error {
	v, err := time.ParseDuration(string(b))
	if err != nil {
		return err
	}
	*d = Duration(v)
	return nil
}

// MarshalText renders the duration.
func (d Duration) MarshalText() ([]byte, error) { return []byte(time.Duration(d).String()), nil }

// D returns the underlying time.Duration.
func (d Duration) D() time.Duration { return time.Duration(d) }

// Default returns the built-in default configuration.
func Default() *Config {
	return &Config{
		Server: Server{
			DataDir: "/var/lib/supp",
			Domain:  "",
		},
		DNS: DNS{
			Upstreams: []Upstream{
				{URL: "doh://dns.quad9.net/dns-query", Weight: 3},
				{URL: "doh://cloudflare-dns.com/dns-query", Weight: 2},
				{URL: "udp://9.9.9.9:53", Weight: 1},
			},
			Bootstrap: []string{"9.9.9.9", "149.112.112.112"},
			Cache: Cache{
				Size:    65536,
				MinTTL:  Duration(60 * time.Second),
				MaxTTL:  Duration(24 * time.Hour),
				FailTTL: Duration(30 * time.Second),
			},
			Listen: Listen{
				Plain: "0.0.0.0:53",
				DoT:   "0.0.0.0:853",
				DoH:   "0.0.0.0:443",
			},
			Timeout: Duration(3 * time.Second),
			EdnsCsr: false,
		},
		Block: Block{
			Enabled: true,
			Lists: []List{
				{Name: "hagezi-normal", URL: "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/domains/native.txt", Format: "domains"},
			},
			Refresh:    Duration(24 * time.Hour),
			BlockIPv6:  true,
			ResponseIP: "0.0.0.0",
		},
		Admin: Admin{
			Enabled: true,
			Listen:  "127.0.0.1:8080",
			Token:   "",
		},
		Log: Log{
			Queries:      true,
			Retention:    Duration(30 * 24 * time.Hour),
			CountersOnly: false,
		},
		WG: WG{
			Enabled:           false,
			Interface:         "supp0",
			Port:              51820,
			Subnet:            "10.66.0.0/24",
			Endpoint:          "",
			DefaultFullTunnel: true,
			SplitNetworks:     []string{},
		},
	}
}

// WGDefaults fills zero fields of the [wg] section with their defaults.
func (w *WG) ApplyDefaults() {
	if w.Interface == "" {
		w.Interface = "supp0"
	}
	if w.Port == 0 {
		w.Port = 51820
	}
	if w.Subnet == "" {
		w.Subnet = "10.66.0.0/24"
	}
}

// EffectiveEndpoint returns the endpoint peers should dial, always
// host:port (the port is appended when the configured value omits it).
func (w *WG) EffectiveEndpoint(domain string) string {
	host := w.Endpoint
	if host == "" {
		host = domain
	}
	if host == "" {
		host = "<server-ip>"
	}
	if _, _, err := net.SplitHostPort(host); err != nil {
		return fmt.Sprintf("%s:%d", host, w.Port)
	}
	return host
}

// Validate checks semantic correctness of the configuration.
func (c *Config) Validate() error {
	if len(c.DNS.Upstreams) == 0 {
		return errors.New("dns.upstreams: at least one upstream is required")
	}
	for i, u := range c.DNS.Upstreams {
		if u.URL == "" {
			return fmt.Errorf("dns.upstreams[%d]: url is required", i)
		}
	}
	if c.DNS.Cache.Size <= 0 {
		return errors.New("dns.cache.size must be > 0")
	}
	if c.Block.Enabled && len(c.Block.Lists) == 0 && len(c.Block.Denylist) == 0 {
		return errors.New("block.enabled with no lists or denylist entries")
	}
	if c.Block.ResponseIP == "" {
		c.Block.ResponseIP = "0.0.0.0"
	}
	if c.DNS.Listen.Plain == "" && c.DNS.Listen.DoT == "" && c.DNS.Listen.DoH == "" {
		return errors.New("all dns listeners disabled; enable at least one")
	}
	c.WG.ApplyDefaults()
	if err := c.WG.Validate(); err != nil {
		return fmt.Errorf("wg: %w", err)
	}
	return nil
}

// Validate checks the [wg] section in isolation.
func (w *WG) Validate() error {
	if !w.Enabled {
		return nil
	}
	if w.Interface == "" {
		return errors.New("interface is required")
	}
	if w.Port < 1 || w.Port > 65535 {
		return fmt.Errorf("port %d out of range", w.Port)
	}
	if _, err := netip.ParsePrefix(strings.TrimSpace(w.Subnet)); err != nil {
		return fmt.Errorf("subnet %q is not a valid CIDR", w.Subnet)
	}
	if len(w.SplitNetworks) > 0 {
		for _, s := range w.SplitNetworks {
			if _, err := netip.ParsePrefix(strings.TrimSpace(s)); err != nil {
				return fmt.Errorf("split_networks: %q is not a valid CIDR", s)
			}
		}
	}
	return nil}

// Load reads a TOML config from path over the defaults.
func Load(path string) (*Config, error) {
	cfg := Default()
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	if err := toml.Unmarshal(b, cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if err := cfg.Validate(); err != nil {
		return nil, err
	}
	return cfg, nil
}

// Save writes the config as TOML to path (creating parent dirs).
func (c *Config) Save(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer f.Close()
	return toml.NewEncoder(f).Encode(c)
}
